baseURL = "https://www.solder.party/"
languageCode = "en-us"
title = "Solder Party"
theme = "docsy"

enableRobotsTXT = true
enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-167782746-1"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
    name = "Lectronz"
    weight = 90
    url = "https://www.lectronz.com/stores/solderparty/"

[[menu.main]]
    name = "Tindie"
    weight = 91
    url = "https://www.tindie.com/stores/arturo182/"

[params]
copyright = "Solder Party AB"
#privacy_policy = "https://policies.google.com/privacy"

# First one is picked as the Twitter card image if not set on page.
#images = ["square-512.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
#version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the
# current doc set.
#version = "1.0"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
#url_latest_version = "https://example.com"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/solderparty/www"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
#github_project_repo = "https://github.com/google/docsy"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
#gcs_engine_id = "016211892546739425471:wlnts24qxbc"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = true

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false

page_meta_links_disabled = true

ul_show = 2

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
#[params.ui.feedback]
#enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
#yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
#no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page,
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.links]

# End user relevant links. These will show up on left side of footer and in the community page if you have one.
#[[params.links.user]]
#	name = "User mailing list"
#	url = "https://example.org/mail"
#	icon = "fa fa-envelope"
#        desc = "Discussion and help from your fellow users"

# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.user]]
	name ="Company Twitter"
	url = "https://twitter.com/solderparty"
	icon = "fab fa-twitter"
	desc = "Follow us on Twitter to get company news!"

[[params.links.user]]
	name ="Artur's Twitter"
	url = "https://twitter.com/arturo182"
	icon = "fab fa-twitter"
	desc = "Follow me on Twitter to get private updates!"

[[params.links.user]]
	name ="Company Bluesky"
	url = "https://bsky.app/profile/solder.party"
	icon = "fa-brands fa-bluesky"
	desc = "Follow us on Bluesky if you prefer!"

[[params.links.user]]
	name ="Instagram"
	url = "https://instagram.com/solderparty"
	icon = "fab fa-instagram"
	desc = "Follow us for pretty PCB photos!"

[[params.links.user]]
	name = "Discord"
	url = "https://discord.gg/myRFTvX"
	icon = "fab fa-discord"
	desc = "Come and join the discussion!"

[[params.links.user]]
	name = "YouTube"
	url = "https://www.youtube.com/arturo182"
	icon = "fab fa-youtube"
	desc = "Subscribe to get notified of our streams!"

[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/solderparty"
	icon = "fab fa-github"
	desc = "Development takes place here!"

[Social]
	twitter = "solderparty"

[[module.imports.mounts]]
	source = "assets/vendor/Font-Awesome/webfonts"
	target = "static/webfonts"
